
FROM python:3.11-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies first 
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port that Streamlit runs on
EXPOSE 8501

# Command to run the Streamlit application
# 'streamlit run' is the command to start your app.
# 'app.py' is the name of your Streamlit application file.
CMD ["streamlit", "run", "app.py"]
